### ISSUE TITLE
How to keep styles of search bar seperate

### ISSUE THREAD

**Issue by skius** [algolia/unified-instantsearch-ecommerce#117]
My shop software (xt:Commerce 6.2) overrides some of the styles of this search bar, see screenshot: ![ss](https://user-images.githubusercontent.com/11870460/81323832-4ed07580-9096-11ea-9152-a056594072ea.png) most notably the font size, "Sort By" label and category buttons/labels.

Is there a way to keep the search window "seperate" (in terms of styles) so these nasty effects don't happen?

Ah didn't see there was already a loosely related issue:  #114

**Comment by sarahdayan** [comment]
Hi @skius!

This is happening because the search experience is injected in your website, and not using something like an `iframe`. Therefore, the styles of your website are "bleeding" into the search experience (since CSS applies globally).

While this is usually desirable (for example, it makes it handy to cascade your font stack), it can also cause issues. What you can try, if your browser supports the feature, is set the following CSS rule:

```css
.uni-Container * {
  all: initial;
}
```

More on this property on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/all).

It may have side effects, so I recommend heavily testing before shipping this to production.

**Comment by skius** [comment]
Hi @sarahdayan thanks for the help.

Sadly the rule doesn't help in my case (neither in Firefox nor Chrome) 
![firefox_23cJS6uCON](https://user-images.githubusercontent.com/11870460/81325484-b5ef2980-9098-11ea-8959-f166daf5a44f.png)

**Comment by skius** [comment]
Just fiddled around with it some more, and the following snippet seems to mostly mitigate the overrides:

```css
html {
	font-size: inherit;
}

.uni-Container input[type="radio"], .uni-Container input[type="checkbox"] {
	margin: 1px 1rem 0 0;
}

.uni-Container b, .uni-Container strong, .uni-Container dt, .uni-Container label, .uni-Container th, .uni-Container .label {
    font-weight: normal;
    font-family: unset;
}
```
